#!/usr/bin/env python3
# Copyright 2026 Careaga Dev
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl-3.0)
"""Genera los data files Odoo del módulo l10n_py_base desde los CSVs canónicos.

Lee ``data/catalogs/dnit/*.csv`` (catálogos canónicos extraídos del Manual
Técnico SIFEN v150) y emite ``addons/l10n_py_base/data/*.{xml,csv}`` en formato
Odoo (con XML IDs deterministas).

Uso:
    python scripts/generate_module_data.py

Las listas chicas (regímenes, tipos de contribuyente, naturaleza, identificación,
departamentos) salen como XML; las grandes (distritos, ciudades) como CSV para
parseo rápido del loader Odoo.
"""
import csv
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
CATALOGS_DIR = ROOT / "data" / "catalogs" / "dnit"
OUT_DIR = ROOT / "addons" / "l10n_py_base" / "data"

# Comentarios al inicio del CSV canónico (líneas que empiezan con '#').
CANONICAL_HEADER = "# Source: data/catalogs/dnit/{src} (Manual Técnico SIFEN v150)"


def _read_canonical(path):
    """Lee un CSV canónico ignorando líneas que empiezan con '#'."""
    with path.open(encoding="utf-8") as fp:
        lines = [line for line in fp if not line.startswith("#")]
    reader = csv.DictReader(lines)
    return list(reader)


def _write_xml(filename, src_name, records_xml):
    out = OUT_DIR / filename
    body = "\n".join(records_xml)
    content = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/generate_module_data.py from data/catalogs/dnit/{src_name} -->
<!-- DO NOT EDIT MANUALLY: re-run the generator to regenerate. -->
<odoo noupdate="1">
{body}
</odoo>
"""
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(records_xml)} records)")


def _write_csv(filename, src_name, fieldnames, rows):
    """Escribe un CSV en formato Odoo (sin comment header — Odoo no lo soporta)."""
    out = OUT_DIR / filename
    with out.open("w", encoding="utf-8", newline="") as fp:
        writer = csv.DictWriter(fp, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)
    print(f"wrote {out.relative_to(ROOT)} ({len(rows)} records, src={src_name})")


def _xml_record(xml_id, model, fields_dict):
    """Construye un <record> XML."""
    lines = [f'    <record id="{xml_id}" model="{model}">']
    for fname, fval in fields_dict.items():
        if isinstance(fval, tuple) and fval[0] == "ref":
            lines.append(f'        <field name="{fname}" ref="{fval[1]}"/>')
        elif isinstance(fval, bool):
            lines.append(f'        <field name="{fname}" eval="{fval}"/>')
        else:
            safe = escape(str(fval))
            lines.append(f'        <field name="{fname}">{safe}</field>')
    lines.append("    </record>")
    return "\n".join(lines)


def gen_regimes():
    src = "regimenes.csv"
    rows = _read_canonical(CATALOGS_DIR / src)
    records = []
    for row in rows:
        if row.get("activo") != "1":
            continue
        records.append(
            _xml_record(
                f"regime_{row['codigo']}",
                "l10n_py.regime",
                {"code": row["codigo"], "name": row["nombre_display"], "active": True},
            )
        )
    _write_xml("l10n_py_regime_data.xml", src, records)


def gen_taxpayer_types():
    src = "tipo_contribuyente.csv"
    rows = _read_canonical(CATALOGS_DIR / src)
    records = []
    for row in rows:
        if row.get("activo") != "1":
            continue
        records.append(
            _xml_record(
                f"taxpayer_type_{row['codigo']}",
                "l10n_py.taxpayer.type",
                {"code": row["codigo"], "name": row["nombre_display"], "active": True},
            )
        )
    _write_xml("l10n_py_taxpayer_type_data.xml", src, records)


def gen_recipient_natures():
    src = "naturaleza_receptor.csv"
    rows = _read_canonical(CATALOGS_DIR / src)
    records = []
    for row in rows:
        if row.get("activo") != "1":
            continue
        records.append(
            _xml_record(
                f"recipient_nature_{row['codigo']}",
                "l10n_py.recipient.nature",
                {"code": row["codigo"], "name": row["nombre_display"], "active": True},
            )
        )
    _write_xml("l10n_py_recipient_nature_data.xml", src, records)


def gen_identification_types():
    """Genera identification types: 7 D208 + el RUC paraguayo."""
    src = "tipo_documento.csv"
    rows = _read_canonical(CATALOGS_DIR / src)
    records = [
        _xml_record(
            "id_type_py_ruc",
            "l10n_latam.identification.type",
            {
                "name": "RUC",
                "country_id": ("ref", "base.py"),
                "l10n_py_is_ruc": True,
                "active": True,
            },
        )
    ]
    slug_map = {
        "1": "cedula_paraguaya",
        "2": "pasaporte",
        "3": "cedula_extranjera",
        "4": "carnet_residencia",
        "5": "innominado",
        "6": "tarjeta_diplomatica",
        "9": "otro",
    }
    for row in rows:
        if row.get("activo") != "1":
            continue
        slug = slug_map.get(row["codigo"], f"d208_{row['codigo']}")
        records.append(
            _xml_record(
                f"id_type_py_{slug}",
                "l10n_latam.identification.type",
                {
                    "name": row["nombre_display"],
                    "country_id": ("ref", "base.py"),
                    "l10n_py_sifen_code": row["codigo"],
                    "active": True,
                },
            )
        )
    _write_xml("l10n_latam_identification_type_data.xml", src, records)


def gen_departments():
    """Departamentos paraguayos como res.country.state.

    XML IDs: ``state_py_<codigo>``.
    """
    src = "departamentos.csv"
    rows = _read_canonical(CATALOGS_DIR / src)
    records = []
    for row in rows:
        if row.get("activo") != "1":
            continue
        records.append(
            _xml_record(
                f"state_py_{row['codigo']}",
                "res.country.state",
                {
                    "name": row["nombre_display"],
                    "code": row["codigo"],
                    "country_id": ("ref", "base.py"),
                    "l10n_py_sifen_code": row["codigo"],
                },
            )
        )
    _write_xml("res_country_state_data.xml", src, records)


def gen_districts():
    """Distritos: CSV pesado, formato Odoo.

    Columnas: id, code, name, state_id:id, active.
    """
    src = "distritos.csv"
    rows = _read_canonical(CATALOGS_DIR / src)
    out_rows = []
    for row in rows:
        if row.get("activo") != "1":
            continue
        state_xml_id = f"l10n_py_base.state_py_{row['codigo_padre']}"
        out_rows.append(
            {
                "id": f"district_py_{row['codigo']}",
                "code": row["codigo"],
                "name": row["nombre_display"],
                "state_id:id": state_xml_id,
                "active": "True",
            }
        )
    _write_csv(
        "l10n_py.district.csv",
        src,
        ["id", "code", "name", "state_id:id", "active"],
        out_rows,
    )


def gen_cities():
    """Ciudades: el catálogo más grande. CSV con FK a distrito.

    Para evitar OOM al cargar 6400+ records, se filtran ciudades activas y se
    incluye el ``state_id`` también (Odoo lo requiere en res.city).
    """
    src_distritos = "distritos.csv"
    src_ciudades = "ciudades.csv"
    # Mapa distrito_codigo -> departamento_codigo (para resolver state_id en cada ciudad)
    distrito_to_state = {}
    for d in _read_canonical(CATALOGS_DIR / src_distritos):
        distrito_to_state[d["codigo"]] = d["codigo_padre"]

    rows = _read_canonical(CATALOGS_DIR / src_ciudades)
    out_rows = []
    skipped = 0
    for row in rows:
        if row.get("activo") != "1":
            continue
        distrito_codigo = row["codigo_padre"]
        state_codigo = distrito_to_state.get(distrito_codigo)
        if not state_codigo:
            skipped += 1
            continue
        out_rows.append(
            {
                "id": f"city_py_{row['codigo']}",
                "name": row["nombre_display"],
                "l10n_py_sifen_code": row["codigo"],
                "l10n_py_district_id:id": f"l10n_py_base.district_py_{distrito_codigo}",
                "state_id:id": f"l10n_py_base.state_py_{state_codigo}",
                "country_id:id": "base.py",
            }
        )
    if skipped:
        print(
            f"WARN: {skipped} ciudades sin distrito padre — omitidas.", file=sys.stderr
        )
    _write_csv(
        "res.city.csv",
        src_ciudades,
        [
            "id",
            "name",
            "l10n_py_sifen_code",
            "l10n_py_district_id:id",
            "state_id:id",
            "country_id:id",
        ],
        out_rows,
    )


def main():
    if not CATALOGS_DIR.is_dir():
        print(f"ERROR: catalog dir not found: {CATALOGS_DIR}", file=sys.stderr)
        sys.exit(1)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    gen_regimes()
    gen_taxpayer_types()
    gen_recipient_natures()
    gen_identification_types()
    gen_departments()
    gen_districts()
    gen_cities()
    print("OK")


if __name__ == "__main__":
    main()
