"""Genera CSVs canónicos de departamentos/distritos/ciudades desde el XLSX DNIT.

Fuente: data/catalogs/_verification/dnit_codigo_referencia_geografica.xlsx
        (CODIGO DE REFERENCIA GEOGRAFICA.xlsx — DNIT 2023)

Esta es la fuente que el Manual Técnico SIFEN v150 (Tabla 2.1) identifica
explícitamente como canónica. El XLSX está desnormalizado: cada fila contiene
los 4 niveles (depto/distrito/ciudad/barrio). Esta script lo normaliza en
3 CSVs con el schema definido en data/catalogs/dnit/README.md.

Uso:
    python scripts/generate_geo_catalogs.py

Output:
    data/catalogs/dnit/departamentos.csv
    data/catalogs/dnit/distritos.csv
    data/catalogs/dnit/ciudades.csv
"""
from __future__ import annotations

import csv
import sys
import unicodedata
from pathlib import Path

try:
    from openpyxl import load_workbook
except ImportError:
    print("ERROR: openpyxl no instalado. pip install --user openpyxl")
    sys.exit(1)


REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_XLSX = REPO_ROOT / "data" / "catalogs" / "_verification" / "dnit_codigo_referencia_geografica.xlsx"
OUT_DIR = REPO_ROOT / "data" / "catalogs" / "dnit"

HEADER_COMMENT = """\
# Source: Manual Técnico SIFEN v150, Tabla 2.1 (DEPARTAMENTOS, DISTRITOS Y CIUDADES)
# Original file: CODIGO DE REFERENCIA GEOGRAFICA.xlsx (DNIT 2023)
# Generated by: scripts/generate_geo_catalogs.py
"""


def ascii_safe(name: str) -> str:
    """Normaliza a UPPERCASE ASCII para matching exacto (sin tildes ni ñ)."""
    nfkd = unicodedata.normalize("NFKD", name)
    no_marks = "".join(c for c in nfkd if not unicodedata.combining(c))
    return no_marks.upper().strip()


def display_name(name: str) -> str:
    """Title-case con tildes preservadas para UI."""
    return name.strip()


def read_dnit_rows() -> list[dict]:
    """Lee el XLSX y devuelve filas como dicts. La col 1 (A) está vacía."""
    wb = load_workbook(SOURCE_XLSX, read_only=True, data_only=True)
    # Excel trunca nombres de hoja a 31 caracteres — el original era
    # "División Político-Administrativa" pero llega como "...Administrativ".
    ws = wb["División Político-Administrativ"]
    rows = list(ws.iter_rows(values_only=True))
    # Header está en la primera fila no vacía. Columnas (1-indexed):
    # A=blank | B=CodDepto | C=NombreDepto | D=CodDistrito | E=NombreDistrito
    # F=CodCiudad | G=NombreCiudad | H=CodBarrio | I=NombreBarrio
    out = []
    for row in rows:
        if not row or len(row) < 7:
            continue
        cod_dep, nom_dep = row[1], row[2]
        cod_dis, nom_dis = row[3], row[4]
        cod_ciu, nom_ciu = row[5], row[6]
        if cod_dep is None or nom_dep is None:
            continue
        # Skip filas de header (texto en columna de código)
        if not isinstance(cod_dep, (int, float)):
            continue
        out.append({
            "cod_dep": int(cod_dep),
            "nom_dep": str(nom_dep).strip(),
            "cod_dis": int(cod_dis) if cod_dis is not None else None,
            "nom_dis": str(nom_dis).strip() if nom_dis else None,
            "cod_ciu": int(cod_ciu) if cod_ciu is not None else None,
            "nom_ciu": str(nom_ciu).strip() if nom_ciu else None,
        })
    return out


def write_csv(path: Path, rows: list[dict], fieldnames: list[str]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        f.write(HEADER_COMMENT)
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            writer.writerow(r)
    return len(rows)


def main() -> int:
    if not SOURCE_XLSX.exists():
        print(f"ERROR: {SOURCE_XLSX} no existe")
        return 1

    print(f"Leyendo {SOURCE_XLSX.name}...")
    rows = read_dnit_rows()
    print(f"  {len(rows)} filas brutas")

    # Departamentos: únicos por cod_dep
    deps_seen: dict[int, dict] = {}
    for r in rows:
        cd = r["cod_dep"]
        if cd not in deps_seen:
            deps_seen[cd] = {
                "codigo": cd,
                "nombre": ascii_safe(r["nom_dep"]),
                "nombre_display": display_name(r["nom_dep"]),
                "codigo_padre": "",
                "activo": 1,
            }
    deps = sorted(deps_seen.values(), key=lambda x: x["codigo"])

    # Distritos: únicos por cod_dis, con codigo_padre = cod_dep
    dis_seen: dict[int, dict] = {}
    for r in rows:
        cd = r["cod_dis"]
        if cd is None or cd in dis_seen:
            continue
        dis_seen[cd] = {
            "codigo": cd,
            "nombre": ascii_safe(r["nom_dis"]) if r["nom_dis"] else "",
            "nombre_display": display_name(r["nom_dis"]) if r["nom_dis"] else "",
            "codigo_padre": r["cod_dep"],
            "activo": 1,
        }
    distritos = sorted(dis_seen.values(), key=lambda x: x["codigo"])

    # Ciudades: únicas por cod_ciu, con codigo_padre = cod_dis
    ciu_seen: dict[int, dict] = {}
    for r in rows:
        cc = r["cod_ciu"]
        if cc is None or cc in ciu_seen:
            continue
        ciu_seen[cc] = {
            "codigo": cc,
            "nombre": ascii_safe(r["nom_ciu"]) if r["nom_ciu"] else "",
            "nombre_display": display_name(r["nom_ciu"]) if r["nom_ciu"] else "",
            "codigo_padre": r["cod_dis"] if r["cod_dis"] is not None else "",
            "activo": 1,
        }
    ciudades = sorted(ciu_seen.values(), key=lambda x: x["codigo"])

    fields = ["codigo", "nombre", "nombre_display", "codigo_padre", "activo"]

    n_dep = write_csv(OUT_DIR / "departamentos.csv", deps, fields)
    n_dis = write_csv(OUT_DIR / "distritos.csv", distritos, fields)
    n_ciu = write_csv(OUT_DIR / "ciudades.csv", ciudades, fields)

    print(f"  -> departamentos.csv: {n_dep}")
    print(f"  -> distritos.csv:     {n_dis}")
    print(f"  -> ciudades.csv:      {n_ciu}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
